api/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.get_data),
]

main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomeView.as_view()),
    path('googlee294f3cea858d890.html', views.Google.as_view()),
    path('yandex_e338a2b8290dc352.html', views.Yandex.as_view()),
    path('sitemap.xml', views.Sitemap.as_view()),
    path('robots.txt', views.Robot.as_view()),
    path('converter/<str:slug>', views.ConverterDetail.as_view(), name='converter-detail'),
    path('convert', views.Convert.as_view(), name='convert')
]

pdfconverter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('main.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models
from . import core


# Create your models here.


class Company(models.Model):
    function_name=models.CharField(max_length=200)
    qid=models.IntegerField()

    def scrape(self, tracking_id):
        result=getattr(core, self.function_name)(tracking_id)
        return result

    def __str__(self):
        return self.function_name

main/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Converter(models.Model):
    title=models.CharField(max_length=200)
    image_file=models.CharField(max_length=200, null=True)
    slug=models.CharField(null=True, max_length=200)
    tag_line=models.TextField(null=True)
    convert_from=models.CharField(max_length=200, null=True)
    description=models.TextField(null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('converter-detail', args=[str(self.slug)])


class subtotpic(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField()
    converter=models.ForeignKey(Converter, on_delete=models.CASCADE)

    def __str__(self):
        return self.converter.title

api/views.py
from django.shortcuts import render
from django.views.generic import View
from .models import Company
from django.http import JsonResponse
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.status import (
    HTTP_400_BAD_REQUEST,
    HTTP_404_NOT_FOUND,
    HTTP_200_OK
)
from rest_framework.response import Response
from django.views.decorators.csrf import csrf_exempt
import pdb

# Create your views here.

@csrf_exempt
@api_view(["GET"])
@permission_classes((AllowAny,))
def get_data(request):
    code = request.GET['code']
    qid = request.GET['company']
    try:
        company = Company.objects.get(qid=qid)
    except :
        return Response({'detail': 'Not Found'}, status=HTTP_404_NOT_FOUND)

    try:
        result = company.scrape(code)
        return Response(result, status=HTTP_200_OK)
    except:
        return Response({'detail': 'Error In Processing,Please check your tracking ID, if problem persist contact Admin '}, status=HTTP_400_BAD_REQUEST)

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic import ListView, DetailView
from .models import Converter
from django.conf import settings
from django.views import View
from django.http import JsonResponse
import requests
from django.core.files.storage import FileSystemStorage
import convertapi
import pdb
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
# Create your views here.


class HomeView(ListView):
    model=Converter
    queryset = Converter.objects.all()
    context_object_name = 'converters'
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context=super(HomeView,self).get_context_data(**kwargs)
        context['title']='PDF Converter - Convert PDF files for free online'
        context['description']='Convert PDF files with our Converter tool - a free online PDF converter. Convert Word to PDF, JPG to PDF, Excel to PDF, HTML to PDF, PNG to PDF, etc.'
        context['thumbnail']='word-to-pdf.png'
        return context

class ConverterDetail(DetailView):
    model=Converter
    context_object_name = 'converter'
    template_name = 'detail.html'

    def get_context_data(self, **kwargs):
        context=super(ConverterDetail,self).get_context_data(**kwargs)
        context['more_tools']=Converter.objects.all().exclude(id=self.object.id)
        context['converters']=Converter.objects.all()
        context['title']='PDF Converter - Convert '+self.object.title+' file for free online'
        context['description']=self.object.description
        context['thumbnail']=self.object.image_file
        return context


@method_decorator(csrf_exempt, 'dispatch')
class Convert(View):


    def get(self, request, *args, **kwargs):
        file_url=request.GET.get('file_url')
        filename=request.GET.get('file_name')
        file_type = filename.split('.').pop()
        response=do_convert(file_url,file_type,filename,'dropbox')
        return JsonResponse(response)


    def post(self, request,*args, **kwargs):
        convertapi.api_secret = settings.API_SECRET
        file=request.FILES['file']
        fs = FileSystemStorage()
        filename = fs.save(file.name, file)
        file_type=filename.split('.').pop()
        uploaded_file_url = fs.url(filename)
        res=do_convert(filename,file_type,filename,'dropzone')
        return JsonResponse(res)


def do_convert(file_url, file_type, file_name, medium):
    convertapi.api_secret = settings.API_SECRET
    #base_url='https://pdftools.projecttopics.org'
    base_directory = settings.MEDIA_ROOT
    try:
        if file_type == 'docx':
            converter = Converter.objects.filter(convert_from=file_type.strip())[0]
        else:
            converter = Converter.objects.get(convert_from=file_type.strip())

    except Converter.DoesNotExist:
        return {'status': 404, 'data': 'Resource not found'}
    #
    # TODO: change file url before upload
    if medium == 'dropzone':
        file_url = '%s/%s' %(base_directory, file_url)
    try:
        upload_io = convertapi.UploadIO(open(file_url, 'rb'))
        result = convertapi.convert('pdf', {'File': upload_io})
        file_url = result.file.url
        return {'status': 200, 'data': file_url}
    except:
        return {'status': 400, 'data': 'API ERROR'}


#C:\Users\tolu\PycharmProjects\pdfconverter\media\Diamond Bank and Access Bank - Outcome of Court Ordered  Shareholders meeting - final 2 (1).docx
class Google(TemplateView):
    template_name = 'googlee294f3cea858d890.html'

class Yandex(TemplateView):
    template_name = 'yandex_e338a2b8290dc352.html'

class Sitemap(TemplateView):
    template_name = 'sitemap.xml'

class Robot(TemplateView):
    template_name = 'robots.txt'

main/templates/detail.html
{% include 'includes/header.html' %}

	<style>
    .container{
        max-width: 1200px;
    }
</style>
    	<main>
    		<div class="container">
            <div class="row" style="margin-top:20px;margin-bottom: 20px">
                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Word to PDF Ad1 -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-2546190987663437"
                         data-ad-slot="3910942540"
                         data-ad-format="link"
                         data-full-width-responsive="true"></ins>
                    <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>

                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <div class="circlediv text-center">
                                <div class="circle detail">
                                    <img src="/static/img/{{ converter.image_file }}" class="img-responsive">
                                </div>
                        </div>
                    </div>
                    <div class="col-sm-9">
                        <h3 style="margin-top:35px; font-weight: 900">{{ converter.title }}</h3>
                        <p>{{ converter.tag_line | default:''}}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 text-center">
                            <form action="/convert" class="dropzone" id="myAwesomeDropzone"></form>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 text-center">

                        <div class="medium">
                            <button class="btn btn-primary upbutton js-upload-btn"><i class="glyphicon glyphicon-plus"></i> Add File</button>
                        </div>
                        <!--img src="/static/img/gdrive.png" class="img-responsive gdrive" width="20px">
                        <img src="/static/img/dropbox.png" class="img-responsive dropbox" width="20px"-->
                        <div id="dropbox-container" class="medium"></div>

                        <h3 class="loading">Converting . . . <img src="/static/img/loading.gif" width="60px"></h3>
                        <div style="width:100%" class="text-center">
                            <a href="#" class="btn btn-primary upbutton download "><i class="glyphicon glyphicon-arrow-down"></i> Download</a>
                            <a href="#" class="btn btn-primary upbutton  dis dis-js"><i class="glyphicon glyphicon-plus"></i> Upload another file</a>


                        </div>

                         <a href="https://dl.dropboxusercontent.com/s/deroi5nwm6u7gdf/advice.png" class="dropbox-saver dropbox download" style="display:none"></a>
                    </div>
                </div>
                 <div class="row" style="margin-top:20px;margin-bottom: 20px">
                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Word to PDF Ad1 -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-2546190987663437"
                         data-ad-slot="3910942540"
                         data-ad-format="link"
                         data-full-width-responsive="true"></ins>
                    <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>

                </div>


                <div class="row">
                    {%  for desc in converter.subtotpic_set.all %}
                    <div class="col-md-4">
                        <h3>{{ desc.title }}</h3>
                        <p>
                           {{ desc.description }}
                        </p>
                    </div>
                    {% endfor %}

                </div>
                <hr class="seperator">

                 <div class="row" style="margin-top:20px;margin-bottom: 20px">
                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Word to PDF Ad1 -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-2546190987663437"
                         data-ad-slot="3910942540"
                         data-ad-format="link"
                         data-full-width-responsive="true"></ins>
                    <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>

                </div>

                <div class="row">
                    <div class="col-md-12">
                        <h4>More Tools</h4>
                    </div>
                </div>



                <div class="row">

                    {%  for converter in more_tools %}
                    <div class="col-md-3">
                        <div class="circlediv text-center">
                            <a href="{{ converter.get_absolute_url }}">
                                <div class="circle detail">
                                    <img src="/static/img/{{ converter.image_file }}" class="img-responsive">
                                </div>
                                {{ converter.title }}
                            </a>
                        </div>
                    </div>
                    {%  endfor %}
                </div>
            </div>
        {%  include 'includes/footer.html' %}
    	</main>
	<script
  			src="https://code.jquery.com/jquery-3.4.1.min.js"
  			></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
        <script src="https://cdn.datatables.net/plug-ins/1.10.19/sorting/datetime-moment.js"></script>
<script>
    $('.js-upload-btn').click(function(e){
        $('.dropzone').trigger('click')
    });
     function show_download_link(data){
        $('.download').css('display', 'block');
        $('.dis').css('display', 'block');
        $('.loading').css('display','none');
        $('.download').attr({'href':data.data});
    }

    $('.dis-js').click(function(e){
        $('.download').css('display', 'none');
        $('.medium').css('display', 'inherit');
        $('.dis').css('display', 'none');
        $('.loading').css('display','none');
    })

    Dropzone.options.myAwesomeDropzone = {
        paramName: "file", // The name that will be used to transfer the file
        maxFiles: 1,
        acceptedFiles:".{{ converter.convert_from }}",
        init:function(){
            this.on('addedfile' ,function(file){
                console.log(file)
                filename=file.name;
                file_ext='.'+filename.split('.').pop()
                extension=".{{ converter.convert_from }}";
                if (extension == file_ext) {
                    $('.medium').css('display', 'none');
                    $('.loading').css('display', 'block')
                }
            })
            this.on('success', function(file,data){
                console.log(data.status);

                if (data.status==200) {
                    show_download_link(data);
                }
                else{
                    alert(data.data)
                    $('.loading').css('display', 'none')
                    $('.medium').css('display','inherit');

                }
            })
        }
    };


    options = {

    // Required. Called when a user selects an item in the Chooser.
    success: function(files) {
        $('.medium').css('display','none');
        $('.loading').css('display', 'block');

        console.log(files[0]);
        file=files[0];

        $.get('/convert', {'file_url':file.link,'file_name':file.name}, function(data){
            if (data.status == 200){
              show_download_link(data)
            }
            else{
                alert(data.data);
                $('.loading').css('display', 'none')
                $('.medium').css('display','inherit');
            }
        });

    },

    // Optional. Called when the user closes the dialog without selecting a file
    // and does not include any parameters.
    cancel: function() {

    },

    // Optional. "preview" (default) is a preview link to the document for sharing,
    // "direct" is an expiring link to download the contents of the file. For more
    // information about link types, see Link types below.
    linkType: "direct", // or "direct"

    // Optional. A value of false (default) limits selection to a single file, while
    // true enables multiple file selection.
    multiselect: false, // or true

    // Optional. This is a list of file extensions. If specified, the user will
    // only be able to select files with these extensions. You may also specify
    // file types, such as "video" or "images" in the list. For more information,
    // see File types below. By default, all extensions are allowed.
    extensions: ['.{{ converter.convert_from }}'],

    // Optional. A value of false (default) limits selection to files,
    // while true allows the user to select both folders and files.
    // You cannot specify `linkType: "direct"` when using `folderselect: true`.
    folderselect: false, // or true

    // Optional. A limit on the size of each file that may be selected, in bytes.
    // If specified, the user will only be able to select files with size
    // less than or equal to this limit.
    // For the purposes of this option, folders have size zero.
   // sizeLimit: 1024, // or any positive number
};
    var button = Dropbox.createChooseButton(options);
    console.log(button)
    document.getElementById("dropbox-container").appendChild(button);
</script>
	</body>
</html>

main/templates/googlee294f3cea858d890.html
google-site-verification: googlee294f3cea858d890.html

main/templates/includes/footer.html
<!-- footer start -->
<footer class="footer-light bg-light">
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-lg-12">
                <div class="row justify-content-center">
                    <div class="title text-center mb-5">

                        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-2546190987663437",
          enable_page_level_ads: true
     });
</script>


                        <h2 class="site-link-footer"></h2>
                        <p class="copyright mt-3">2019 © Recode Limited.</p>
                        <p>All rights reserved</p>
                        <!--ul class="footer-texts list-inline mb-2">
                            <li class="list-inline-item"><a href="#" class="">Privacy</a></li>
                            <li class="list-inline-item"><a href="#" class="">Terms & Conditions</a></li>
                        </ul-->
                    </div>



                </div>
            </div>
        </div>
    </div>
</footer>
<!-- footer end -->

main/templates/includes/header.html
<!DOCTYPE html>
<html>
	<head>
        <title>{{ title }} </title>
	    <meta charset="utf-8" />
	    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="{{ description }}">
        <meta property="og:locale" content="en" />
        <meta property="og:site_name" content="PDF Converter">
        <meta property="og:title" content="{{ title }}">
        <meta property="og:description" content="{{ description }}">
        <meta property="og:image" content="https://pdftools.projecttopics.org/static/img/{{ thumbnail }}">
        <meta name="robots" content="index,follow">
        <link rel="shortcut icon" href="/static/img/favicon.png">
	    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" typpe="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
	    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
	    <link href="/static/style.css" rel="stylesheet">
	    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic" rel="stylesheet" type="text/css" />
	    <link href="https://fonts.googleapis.com/css?family=Comfortaa:300,400,500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet">
        <script src="https://rawgit.com/enyo/dropzone/master/dist/dropzone.js"></script>
        <script type="text/javascript" src="https://www.dropbox.com/static/api/2/dropins.js" id="dropboxjs" data-app-key="ws88tqx0q7y932h"></script>
    <link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">
    </head>
    <body>
    <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-136701175-1"></script>
        <script>
          window.dataLayer = window.dataLayer|| [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-136701175-1');
        </script>
    	<header>
    		<nav class="navbar card">
			  <div class="container-fluid">
			    <div class="navbar-header">
			    	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				      </button>
			      <a class="navbar-brand" href="/"><img class="logo" src="/static/img/nlogo.png"></a>
			    </div>
			    <div class="collapse navbar-collapse" id="myNavbar">
				    <ul class="nav navbar-nav">
                        {%  for converter in converters %}
				      <li><a href="{{ converter.get_absolute_url }}">{{ converter.title }} </a></li>
				        {%  endfor %}
				    </ul>
				</div>
			  </div>
			</nav>
    	</header><!--content-->

main/templates/index.html
{% include 'includes/header.html' %}
    	<main>
    		<div class="container">
            <div class="row" style="margin-top:20px;margin-bottom: 20px">
                <div class="col-md-12">
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Word to PDF Ad -->
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-2546190987663437"
                     data-ad-slot="6821366284"
                     data-ad-format="auto"
                     data-full-width-responsive="true"></ins>
                <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
                </div>

            </div>

    			<div class="row">
                    {%  for converter in converters %}
    				<div class="col-md-4 col-sm-4 col-xs-6">
    					<div class="circlediv text-center">
    						<a href="{{ converter.get_absolute_url }}">
    							<div class="circle">
    								<img src="/static/img/{{ converter.image_file }}" class="img-responsive">
    							</div>
    							{{ converter.title }}
    						</a>
    					</div>
    				</div>
                    {%  endfor %}
    			</div>
            <div class="row" style="margin-top:20px;margin-bottom: 20px">
                <div class="col-md-12">
                 <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Word to PDF Ad -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-2546190987663437"
                         data-ad-slot="6821366284"
                         data-ad-format="auto"
                         data-full-width-responsive="true"></ins>
                    <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                </div>
            </div>
    		</div>
        {%  include 'includes/footer.html' %}
    	</main>
	<script
  			src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
        <script src="https://cdn.datatables.net/plug-ins/1.10.19/sorting/datetime-moment.js"></script>
	</body>
</html>

main/templates/yandex_e338a2b8290dc352.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body>Verification: e338a2b8290dc352</body>
</html>